//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorktrackerEntities : DbContext
    {
        public WorktrackerEntities()
            : base("name=WorktrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WorkOut_Activess> WorkOut_Activess { get; set; }
        public virtual DbSet<workout_categories> workout_categories { get; set; }
        public virtual DbSet<WorkOut_Collectionsss> WorkOut_Collectionsss { get; set; }
    }
}
