//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOut_Collectionsss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOut_Collectionsss()
        {
            this.WorkOut_Activess = new HashSet<WorkOut_Activess>();
        }
    
        public string WorkOut_Title { get; set; }
        public string WorkOut_Note { get; set; }
        public Nullable<double> Calories_Burn_Per_Minute { get; set; }
        public Nullable<int> Category_id { get; set; }
        public int WorkOut_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOut_Activess> WorkOut_Activess { get; set; }
        public virtual workout_categories workout_categories { get; set; }
    }
}
