//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOut_Activess
    {
        public int id { get; set; }
        public Nullable<int> WorkOut_id { get; set; }
        public Nullable<System.TimeSpan> Start_time { get; set; }
        public Nullable<System.DateTime> Starts_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Statuss { get; set; }
    
        public virtual WorkOut_Collectionsss WorkOut_Collectionsss { get; set; }
    }
}
